pipeline {
    agent {
        kubernetes {
            cloud 'DockerDesktop'
            inheritFrom 'terraform-agent'
        }
    }

    parameters {
        choice(
            name: 'ACTION',
            choices: ['apply', 'destroy'],
            description: 'Choose the action to perform'
        )

        string(
            name: 'ENVIRONMENT',
            defaultValue: 'dev',
            description: 'Specify the environment'
        )
    }

        environment {
            TERRAFORM_DIR     = 'eks-infra-code'
            AWS_PROFILE       = 'jhansi'
            AWS_CONFIG_FILE   = '/home/jenkins/.aws/config'
            AWS_SHARED_CREDENTIALS_FILE = '/home/jenkins/.aws/credentials'
        }

    stages {
        stage('Test AWS Access') {
    steps {
        container('terraform') {
            sh '''
                ls -la /home/jenkins/.aws
                aws sts get-caller-identity --profile "$AWS_PROFILE"
            '''
        }
    }
}
        stage('Code Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Terraform Init') {
            steps {
                container('terraform') {
                    dir("${TERRAFORM_DIR}") {
                        sh 'terraform init'
                    }
                }
            }
        }

        stage('Terraform Plan') {
            steps {
                container('terraform') {
                    dir("${TERRAFORM_DIR}") {
                        sh 'terraform plan'
                    }
                }
            }
        }
    }

    post {
        success {
            echo 'Succeeded'
        }

        failure {
            echo 'Failed'
        }

        unstable {
            echo 'Unstable'
        }

        always {
            cleanWs()
        }
    }
}